I'm sorry, but an uncaught exception occurred.

While executing init code:
  File "game/battle.rpy", line 8, in script
    $ spirit1Image = renpy.image(im.Scale("assets/cPers.png", 180, 200))
  File "game/battle.rpy", line 8, in <module>
    $ spirit1Image = renpy.image(im.Scale("assets/cPers.png", 180, 200))
TypeError: image() takes exactly 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/battle.rpy", line 8, in script
    $ spirit1Image = renpy.image(im.Scale("assets/cPers.png", 180, 200))
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\ast.py", line 756, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/battle.rpy", line 8, in <module>
    $ spirit1Image = renpy.image(im.Scale("assets/cPers.png", 180, 200))
TypeError: image() takes exactly 2 arguments (1 given)

Windows-7-6.1.7601-SP1
Ren'Py 6.17.6.512
House Guard 0.0
