I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script call
    call battle(bossBattle = True)
  File "game/battle.rpy", line 201, in script
    label battle(leader = vesto, party = spirits, boss = None, enemies = banes):
Exception: Unknown keyword arguments: bossBattle

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script call
    call battle(bossBattle = True)
  File "game/battle.rpy", line 201, in script
    label battle(leader = vesto, party = spirits, boss = None, enemies = banes):
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\ast.py", line 703, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\ast.py", line 142, in apply_arguments
    return parameters.apply(args, kwargs)
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\ast.py", line 130, in apply
    raise Exception("Unknown keyword arguments: %s" % ( ", ".join(values.keys())))
Exception: Unknown keyword arguments: bossBattle

Windows-7-6.1.7601-SP1
Ren'Py 6.17.7.521
House Guard 0.0
